<footer class="footer_area">

	<div class="footer_bottom">
		<div class="container">
			<div class="row">
				<div class="col-sm-4">
					<p>© 2015 FUNIX. All rights reserved</p>
				</div>
				<div class="col-sm-8">
					<nav class="footer_menu">
						<ul>
							<li><a href="index.html">Home</a></li>
							<li><a href="mentor.html">Mentor</a></li>
							<li><a href="http://cyberlms.fpt.edu.vn/">Course</a></li>
							<li><a href="about.html">About</a></li>
						</ul>
					</nav>
				</div>
			</div>
		</div>
	</div>
</footer>
<script type='text/javascript'>window._sbzq||function(e){e._sbzq=[];var t=e._sbzq;t.push(["_setAccount",27228]);var n=e.location.protocol=="https:"?"https:":"http:";var r=document.createElement("script");r.type="text/javascript";r.async=true;r.src=n+"//static.subiz.com/public/js/loader.js";var i=document.getElementsByTagName("script")[0];i.parentNode.insertBefore(r,i)}(window);</script>